"""Configuration templates for tc-limit setup.

Edit this file to add or modify presets.
Values are in the unified unit convention:
  - Time:  seconds
  - Bandwidth: Mbps
  - Traffic: MB
"""

# Key names match the YAML config structure (flat for the template generator).
TEMPLATES: dict[str, dict[str, object]] = {
    "default": {
        "limits.higher": 150,
        "limits.lower": 110,
        "limits.threshold": 120,
        "window.duration": 5 * 60,
        "window.interval": 10,
        "cooldown": 3 * 60,
        "recovery_steps": 1,
        "burst.enabled": True,
        "burst.window": 3 * 60,
        "burst.threshold_mb": 2 * 1000,
        "network.interface": "",
        "network.burst_kbit": 16,
    },
    "light": {
        "limits.higher": 75,
        "limits.lower": 20,
        "limits.threshold": 30,
        "window.duration": 5 * 60,
        "window.interval": 5,
        "cooldown": 3 * 60,
        "recovery_steps": 2,
        "burst.enabled": True,
        "burst.window": 2 * 60,
        "burst.threshold_mb": 700,
        "network.interface": "",
        "network.burst_kbit": 16,
    },
}


def generate_yaml(template_name: str) -> str:
    """Generate config.yaml content from a named template."""
    t = TEMPLATES.get(template_name)
    if t is None:
        available = ", ".join(TEMPLATES.keys())
        raise ValueError(f"Unknown template {template_name!r}. Available: {available}")

    def get(path: str, default=None):
        return t.get(path, default)

    return f"""\
# tc-limit — Smart Bandwidth Limit Daemon
# Generated by setup.sh --template {template_name}

# ── Bandwidth Limits ──
limits:
  higher:    {get("limits.higher")}       # Mbps — normal operating rate
  lower:     {get("limits.lower")}        # Mbps — limited rate
  threshold: {get("limits.threshold")}    # Mbps — alert line

# ── Sampling Window ──
window:
  duration:  {get("window.duration")}     # seconds
  interval:  {get("window.interval")}     # seconds

# ── Burst Detection ──
burst:
  enabled:      {str(get("burst.enabled")).lower()}
  window:       {get("burst.window")}     # seconds
  threshold_mb: {get("burst.threshold_mb")} # MB

cooldown:       {get("cooldown")}         # seconds
recovery_steps: {get("recovery_steps")}   # number of ramp steps (1 = instant)

# ── Network ──
network:
  interface: ""        # empty = auto-detect
  burst_kbit: {get("network.burst_kbit")}

# ── Runtime ──
runtime:
  dry_run:   false
  log_level: "INFO"
  state_file: "/run/tc-limit/state.json"
  pid_file:   "/run/tc-limit/daemon.pid"

# ── Storage ──
storage:
  enabled: false
  path: "/var/lib/tc-limit/metrics.db"
  commit_interval: 60
  retention_days: 90
"""
